name: RSpec and RuboCop

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  rubocop:
    name: Run RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3 # Specify the Ruby version you want to use
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      
      - name: Run RuboCop
        run: bundle exec rubocop

  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3 # Specify the Ruby version you want to use
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      
      - name: Run RSpec
        run: bundle exec rspec
